part of 'communicate.dart';

const coreMenu = <AacItem>[
  AacItem(
    label: 'People words',
    icon: Icons.person,
    color: Colors.blue,
    tileColor: Color(0xFFE3F2FD),
    children: corePronouns,
  ),
  AacItem(
    label: 'Verbs',
    icon: Icons.directions_run,
    color: Colors.green,
    tileColor: Color(0xFFE8F5E9),
    children: coreVerbs,
  ),
  AacItem(
    label: 'Describe',
    icon: Icons.tune,
    color: Colors.orange,
    tileColor: Color(0xFFFFF3E0),
    children: coreDescribe,
  ),
  AacItem(
    label: 'Ask',
    icon: Icons.help_outline,
    color: Colors.indigo,
    tileColor: Color(0xFFE8EAF6),
    children: coreQuestions,
  ),
  AacItem(
    label: 'Location',
    icon: Icons.place,
    color: Colors.teal,
    tileColor: Color(0xFFE0F2F1),
    children: coreLocation,
  ),
  AacItem(
    label: 'Time',
    icon: Icons.schedule,
    color: Colors.purple,
    tileColor: Color(0xFFF3E5F5),
    children: coreTime,
  ),
  AacItem(
    label: 'Social',
    icon: Icons.handshake,
    color: Colors.pink,
    tileColor: Color(0xFFFCE4EC),
    children: coreSocial,
  ),
  AacItem(
    label: 'Grammar',
    icon: Icons.text_fields,
    color: Colors.blueGrey,
    tileColor: Color(0xFFECEFF1),
    children: coreGrammar,
  ),
  AacItem(
    label: 'Helpers',
    icon: Icons.extension,
    color: Colors.blueGrey,
    tileColor: Color(0xFFECEFF1),
    children: coreHelpers,
  ),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const corePronouns = <AacItem>[
  AacItem.word('I', icon: Icons.person, color: Colors.blue),
  AacItem.word('you', icon: Icons.person_outline, color: Colors.blue),
  AacItem.word('he', icon: Icons.man, color: Colors.blue),
  AacItem.word('she', icon: Icons.woman, color: Colors.blue),
  AacItem.word('it', icon: Icons.circle_outlined, color: Colors.blue),
  AacItem.word('we', icon: Icons.groups, color: Colors.blue),
  AacItem.word('they', icon: Icons.people, color: Colors.blue),
  AacItem.word('me', icon: Icons.accessibility_new, color: Colors.blue),
  AacItem.word('my', icon: Icons.badge, color: Colors.blue),
  AacItem.word('your', icon: Icons.assignment_ind, color: Colors.blue),
  AacItem.word('him', icon: Icons.man, color: Colors.blue),
  AacItem.word('her', icon: Icons.woman, color: Colors.blue),
  AacItem.word('them', icon: Icons.people_outline, color: Colors.blue),
  AacItem.word('us', icon: Icons.groups, color: Colors.blue),
  AacItem.word('our', icon: Icons.family_restroom, color: Colors.blue),
  AacItem.word('this', icon: Icons.touch_app, color: Colors.blue),
  AacItem.word('that', icon: Icons.back_hand, color: Colors.blue),
  AacItem.word('these', icon: Icons.filter_none, color: Colors.blue),
  AacItem.word('those', icon: Icons.collections, color: Colors.blue),
  AacItem.word('someone', icon: Icons.person_search, color: Colors.blue),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const coreVerbs = <AacItem>[
  AacItem.word('am', icon: Icons.person, color: Colors.green),
  AacItem.word('feel', icon: Icons.favorite, color: Colors.green),
  AacItem.word('want', icon: Icons.favorite_border, color: Colors.green),
  AacItem.word('need', icon: Icons.priority_high, color: Colors.green),
  AacItem.word('like', icon: Icons.thumb_up, color: Colors.green),
  AacItem.word('go', icon: Icons.directions_walk, color: Colors.green),
  AacItem.word('get', icon: Icons.download, color: Colors.green),
  AacItem.word('do', icon: Icons.play_arrow, color: Colors.green),
  AacItem.word('make', icon: Icons.build, color: Colors.green),
  AacItem.word('know', icon: Icons.lightbulb, color: Colors.green),
  AacItem.word('think', icon: Icons.psychology, color: Colors.green),
  AacItem.word('see', icon: Icons.visibility, color: Colors.green),
  AacItem.word('say', icon: Icons.record_voice_over, color: Colors.green),
  AacItem.word('have', icon: Icons.inventory_2, color: Colors.green),
  AacItem.word('give', icon: Icons.redeem, color: Colors.green),
  AacItem.word('put', icon: Icons.place, color: Colors.green),
  AacItem.word('take', icon: Icons.back_hand, color: Colors.green),
  AacItem.word('help', icon: Icons.help, color: Colors.green),
  AacItem.word('come', icon: Icons.login, color: Colors.green),
  AacItem.word('eat', icon: Icons.restaurant, color: Colors.green),
  AacItem.word('drink', icon: Icons.local_drink, color: Colors.green),
  AacItem.word('sleep', icon: Icons.bedtime, color: Colors.green),
  AacItem.word('look', icon: Icons.search, color: Colors.green),
  AacItem.word('find', icon: Icons.find_in_page, color: Colors.green),
  AacItem.word('tell', icon: Icons.campaign, color: Colors.green),
  AacItem.word('ask', icon: Icons.help_outline, color: Colors.green),
  AacItem.word('try', icon: Icons.replay, color: Colors.green),
  AacItem.word('open', icon: Icons.lock_open, color: Colors.green),
  AacItem.word('close', icon: Icons.lock, color: Colors.green),
  AacItem.word('sit', icon: Icons.chair, color: Colors.green),
  AacItem.word('stand', icon: Icons.accessibility_new, color: Colors.green),
  AacItem.word('walk', icon: Icons.directions_walk, color: Colors.green),
  AacItem.word('talk', icon: Icons.chat, color: Colors.green),
  AacItem.word('call', icon: Icons.call, color: Colors.green),
  AacItem.word('use', icon: Icons.touch_app, color: Colors.green),
  AacItem.word('turn', icon: Icons.rotate_right, color: Colors.green),
  AacItem.word('leave', icon: Icons.logout, color: Colors.green),
  AacItem.word('rest', icon: Icons.hotel, color: Colors.green),
  AacItem.word('hurt', icon: Icons.healing, color: Colors.green),
  AacItem.word('start', icon: Icons.play_arrow, color: Colors.green),
  AacItem.word('bring', icon: Icons.shopping_bag, color: Colors.green),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const coreDescribe = <AacItem>[
  AacItem.word('more', icon: Icons.add, color: Colors.orange),
  AacItem.word('all', icon: Icons.select_all, color: Colors.orange),
  AacItem.word('some', icon: Icons.filter_none, color: Colors.orange),
  AacItem.word('same', icon: Icons.compare, color: Colors.orange),
  AacItem.word('different', icon: Icons.difference, color: Colors.orange),
  AacItem.word('good', icon: Icons.sentiment_satisfied, color: Colors.orange),
  AacItem.word('bad', icon: Icons.sentiment_dissatisfied, color: Colors.orange),
  AacItem.word('big', icon: Icons.zoom_out_map, color: Colors.orange),
  AacItem.word('little', icon: Icons.zoom_in_map, color: Colors.orange),
  AacItem.word('hot', icon: Icons.local_fire_department, color: Colors.orange),
  AacItem.word('cold', icon: Icons.ac_unit, color: Colors.orange),
  AacItem.word('fast', icon: Icons.speed, color: Colors.orange),
  AacItem.word('slow', icon: Icons.slow_motion_video, color: Colors.orange),
  AacItem.word('new', icon: Icons.fiber_new, color: Colors.orange),
  AacItem.word('old', icon: Icons.hourglass_empty, color: Colors.orange),
  AacItem.word('easy', icon: Icons.sentiment_satisfied, color: Colors.orange),
  AacItem.word('hard', icon: Icons.fitness_center, color: Colors.orange),
  AacItem.word('ready', icon: Icons.check_circle, color: Colors.orange),
  AacItem.word('done', icon: Icons.task_alt, color: Colors.orange),
  AacItem.word('enough', icon: Icons.sports_score, color: Colors.orange),
  AacItem.word('right', icon: Icons.check, color: Colors.orange),
  AacItem.word('wrong', icon: Icons.close, color: Colors.orange),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const coreQuestions = <AacItem>[
  AacItem.word('what', icon: Icons.help_outline, color: Colors.indigo),
  AacItem.word('where', icon: Icons.place, color: Colors.indigo),
  AacItem.word('when', icon: Icons.schedule, color: Colors.indigo),
  AacItem.word('who', icon: Icons.person_search, color: Colors.indigo),
  AacItem.word('why', icon: Icons.help_center, color: Colors.indigo),
  AacItem.word('how', icon: Icons.settings, color: Colors.indigo),
  AacItem.word('which', icon: Icons.rule, color: Colors.indigo),
  AacItem.word('whose', icon: Icons.badge, color: Colors.indigo),
  AacItem.word('can', icon: Icons.verified, color: Colors.indigo),
  AacItem.word('do', icon: Icons.play_arrow, color: Colors.indigo),
  AacItem.word('did', icon: Icons.history, color: Colors.indigo),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const coreLocation = <AacItem>[
  AacItem.word('in', icon: Icons.login, color: Colors.teal),
  AacItem.word('on', icon: Icons.horizontal_rule, color: Colors.teal),
  AacItem.word('off', icon: Icons.power_settings_new, color: Colors.teal),
  AacItem.word('up', icon: Icons.arrow_upward, color: Colors.teal),
  AacItem.word('down', icon: Icons.arrow_downward, color: Colors.teal),
  AacItem.word('with', icon: Icons.group, color: Colors.teal),
  AacItem.word('for', icon: Icons.volunteer_activism, color: Colors.teal),
  AacItem.word('to', icon: Icons.east, color: Colors.teal),
  AacItem.word('from', icon: Icons.west, color: Colors.teal),
  AacItem.word('at', icon: Icons.my_location, color: Colors.teal),
  AacItem.word('under', icon: Icons.expand_more, color: Colors.teal),
  AacItem.word('over', icon: Icons.expand_less, color: Colors.teal),
  AacItem.word('out', icon: Icons.logout, color: Colors.teal),
  AacItem.word('around', icon: Icons.sync, color: Colors.teal),
  AacItem.word('near', icon: Icons.near_me, color: Colors.teal),
  AacItem.word('here', icon: Icons.place, color: Colors.teal),
  AacItem.word('there', icon: Icons.flag, color: Colors.teal),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const coreTime = <AacItem>[
  AacItem.word('now', icon: Icons.bolt, color: Colors.purple),
  AacItem.word('later', icon: Icons.schedule, color: Colors.purple),
  AacItem.word('before', icon: Icons.undo, color: Colors.purple),
  AacItem.word('after', icon: Icons.redo, color: Colors.purple),
  AacItem.word('again', icon: Icons.replay, color: Colors.purple),
  AacItem.word('first', icon: Icons.looks_one, color: Colors.purple),
  AacItem.word('next', icon: Icons.skip_next, color: Colors.purple),
  AacItem.word('last', icon: Icons.last_page, color: Colors.purple),
  AacItem.word('today', icon: Icons.today, color: Colors.purple),
  AacItem.word('tomorrow', icon: Icons.event, color: Colors.purple),
  AacItem.word('yesterday', icon: Icons.history, color: Colors.purple),
  AacItem.word('always', icon: Icons.all_inclusive, color: Colors.purple),
  AacItem.word('never', icon: Icons.block, color: Colors.purple),
  AacItem.word('sometimes', icon: Icons.more_horiz, color: Colors.purple),
  AacItem.word('soon', icon: Icons.upcoming, color: Colors.purple),
  AacItem.word('still', icon: Icons.pause, color: Colors.purple),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const coreSocial = <AacItem>[
  AacItem.word('please', icon: Icons.front_hand, color: Colors.pink),
  AacItem.word('thank you', icon: Icons.favorite, color: Colors.pink),
  AacItem.word('sorry', icon: Icons.handshake, color: Colors.pink),
  AacItem.word('hello', icon: Icons.waving_hand, color: Colors.pink),
  AacItem.word('goodbye', icon: Icons.waving_hand, color: Colors.pink),
  AacItem.word('okay', icon: Icons.thumb_up, color: Colors.pink),
  AacItem.word('stop', icon: Icons.stop_circle, color: Colors.pink),
  AacItem.word('wait', icon: Icons.pause_circle, color: Colors.pink),
  AacItem.word('help', icon: Icons.help, color: Colors.pink),
  AacItem.word('finished', icon: Icons.check_circle, color: Colors.pink),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const coreGrammar = <AacItem>[
  AacItem.word('a', icon: Icons.title, color: Colors.blueGrey),
  AacItem.word('an', icon: Icons.title, color: Colors.blueGrey),
  AacItem.word('the', icon: Icons.text_fields, color: Colors.blueGrey),
  AacItem.word('and', icon: Icons.add, color: Colors.blueGrey),
  AacItem.word('or', icon: Icons.alt_route, color: Colors.blueGrey),
  AacItem.word('but', icon: Icons.swap_horiz, color: Colors.blueGrey),
  AacItem.word('because', icon: Icons.link, color: Colors.blueGrey),
  AacItem.word('if', icon: Icons.call_split, color: Colors.blueGrey),
  AacItem.word('not', icon: Icons.block, color: Colors.blueGrey),
  AacItem.word("don't", icon: Icons.do_not_disturb, color: Colors.blueGrey),
  AacItem.word("can't", icon: Icons.not_interested, color: Colors.blueGrey),
  AacItem.word('can', icon: Icons.verified, color: Colors.blueGrey),
  AacItem.word('will', icon: Icons.forward, color: Colors.blueGrey),
  AacItem.word('is', icon: Icons.check, color: Colors.blueGrey),
  AacItem.word('are', icon: Icons.done_all, color: Colors.blueGrey),
  AacItem.word('was', icon: Icons.history, color: Colors.blueGrey),
  AacItem.word('be', icon: Icons.circle_outlined, color: Colors.blueGrey),
  AacItem.word('did', icon: Icons.replay, color: Colors.blueGrey),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const coreHelpers = <AacItem>[
  AacItem.word('am', icon: Icons.person, color: Colors.blueGrey),
  AacItem.word('feel', icon: Icons.favorite, color: Colors.blueGrey),
  AacItem.word('of', icon: Icons.category, color: Colors.blueGrey),
  AacItem.word('about', icon: Icons.info, color: Colors.blueGrey),
  AacItem.word('so', icon: Icons.south_east, color: Colors.blueGrey),
  AacItem.word('then', icon: Icons.subdirectory_arrow_right, color: Colors.blueGrey),
  AacItem.word('just', icon: Icons.exposure_zero, color: Colors.blueGrey),
  AacItem.word('also', icon: Icons.add_circle_outline, color: Colors.blueGrey),
  AacItem.word('too', icon: Icons.exposure_plus_1, color: Colors.blueGrey),
  AacItem.word('very', icon: Icons.priority_high, color: Colors.blueGrey),
  AacItem.word('really', icon: Icons.star, color: Colors.blueGrey),
  AacItem.word('maybe', icon: Icons.help_outline, color: Colors.blueGrey),
  AacItem.word('this', icon: Icons.touch_app, color: Colors.blueGrey),
  AacItem.word('that', icon: Icons.back_hand, color: Colors.blueGrey),
  AacItem.word('here', icon: Icons.place, color: Colors.blueGrey),
  AacItem.word('there', icon: Icons.flag, color: Colors.blueGrey),
  AacItem.word('than', icon: Icons.compare_arrows, color: Colors.blueGrey),
  AacItem.word('as', icon: Icons.drag_handle, color: Colors.blueGrey),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const topicsMenu = <AacItem>[
  AacItem(
    label: 'Food',
    icon: Icons.restaurant,
    color: Colors.orange,
    tileColor: Color(0xFFFFF3E0),
    children: fringeFood,
  ),
  AacItem(
    label: 'Places',
    icon: Icons.place,
    color: Colors.teal,
    tileColor: Color(0xFFE0F2F1),
    children: fringePlaces,
  ),
  AacItem(
    label: 'Things',
    icon: Icons.widgets,
    color: Colors.brown,
    tileColor: Color(0xFFEFEBE9),
    children: fringeThings,
  ),
  AacItem(
    label: 'People',
    icon: Icons.groups,
    color: Colors.pink,
    tileColor: Color(0xFFFCE4EC),
    children: fringePeople,
  ),
  AacItem(
    label: 'Time',
    icon: Icons.calendar_month,
    color: Colors.purple,
    tileColor: Color(0xFFF3E5F5),
    children: fringeTime,
  ),
  AacItem(
    label: 'Leisure',
    icon: Icons.sports_esports,
    color: Colors.deepPurple,
    tileColor: Color(0xFFEDE7F6),
    children: fringeLeisure,
  ),
  AacItem(
    label: 'Phrases',
    icon: Icons.chat_bubble,
    color: Colors.indigo,
    tileColor: Color(0xFFE8EAF6),
    children: fringePhrases,
  ),
  AacItem(
    label: 'Religion',
    icon: Icons.church,
    color: Colors.purple,
    tileColor: Color(0xFFF3E5F5),
    children: fringeReligion,
  ),
  AacItem(
    label: 'School',
    icon: Icons.school,
    color: Colors.blue,
    tileColor: Color(0xFFE3F2FD),
    children: fringeSchool,
  ),
  AacItem(
    label: 'Sport',
    icon: Icons.sports_soccer,
    color: Colors.green,
    tileColor: Color(0xFFE8F5E9),
    children: fringeSport,
  ),
  AacItem(
    label: 'Adjectives',
    icon: Icons.palette,
    color: Colors.orange,
    tileColor: Color(0xFFFFF3E0),
    children: fringeAdjectives,
  ),
  AacItem(
    label: 'Action verbs',
    icon: Icons.directions_run,
    color: Colors.green,
    tileColor: Color(0xFFE8F5E9),
    children: fringeVerbs,
  ),
  AacItem(
    label: 'Create',
    icon: Icons.brush,
    color: Colors.pink,
    tileColor: Color(0xFFFCE4EC),
    children: fringeCreate,
  ),
  AacItem(
    label: 'Daily life',
    icon: Icons.home,
    color: Colors.teal,
    tileColor: Color(0xFFE0F2F1),
    children: fringeDailyLife,
  ),
  AacItem(
    label: "Let's talk",
    icon: Icons.forum,
    color: Colors.indigo,
    tileColor: Color(0xFFE8EAF6),
    children: fringeLetsTalk,
  ),
  AacItem(
    label: 'Motor play',
    icon: Icons.sports_handball,
    color: Colors.deepOrange,
    tileColor: Color(0xFFFBE9E7),
    children: fringeMotorPlay,
  ),
  AacItem(
    label: 'Out & about',
    icon: Icons.explore,
    color: Colors.blue,
    tileColor: Color(0xFFE3F2FD),
    children: fringeOutAbout,
  ),
  AacItem(
    label: 'Reading',
    icon: Icons.menu_book,
    color: Colors.brown,
    tileColor: Color(0xFFEFEBE9),
    children: fringeReading,
  ),
  AacItem(
    label: 'Toys & games',
    icon: Icons.toys,
    color: Colors.amber,
    tileColor: Color(0xFFFFF8E1),
    children: fringeToys,
  ),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeFood = <AacItem>[
  AacItem.word('breakfast', icon: Icons.free_breakfast, color: Colors.orange),
  AacItem.word('lunch', icon: Icons.lunch_dining, color: Colors.orange),
  AacItem.word('dinner', icon: Icons.dinner_dining, color: Colors.orange),
  AacItem.word('snack', icon: Icons.cookie, color: Colors.orange),
  AacItem.word('water', icon: Icons.water_drop, color: Colors.blue),
  AacItem.word('juice', icon: Icons.local_drink, color: Colors.orange),
  AacItem.word('milk', icon: Icons.local_cafe, color: Colors.blueGrey),
  AacItem.word('coffee', icon: Icons.coffee, color: Colors.brown),
  AacItem.word('tea', icon: Icons.emoji_food_beverage, color: Colors.green),
  AacItem.word('fruit', icon: Icons.apple, color: Colors.red),
  AacItem.word('apple', icon: Icons.apple, color: Colors.red),
  AacItem.word('banana', icon: Icons.eco, color: Colors.amber),
  AacItem.word('bread', icon: Icons.bakery_dining, color: Colors.brown),
  AacItem.word('sandwich', icon: Icons.lunch_dining, color: Colors.orange),
  AacItem.word('soup', icon: Icons.soup_kitchen, color: Colors.brown),
  AacItem.word('salad', icon: Icons.grass, color: Colors.green),
  AacItem.word('pasta', icon: Icons.ramen_dining, color: Colors.orange),
  AacItem.word('rice', icon: Icons.rice_bowl, color: Colors.brown),
  AacItem.word('chicken', icon: Icons.set_meal, color: Colors.orange),
  AacItem.word('pizza', icon: Icons.local_pizza, color: Colors.red),
  AacItem.word('ice cream', icon: Icons.icecream, color: Colors.pink),
  AacItem.word('cookie', icon: Icons.cookie, color: Colors.brown),
  AacItem.word('egg', icon: Icons.egg, color: Colors.amber),
  AacItem.word('yogurt', icon: Icons.icecream, color: Colors.pink),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringePlaces = <AacItem>[
  AacItem.word('home', icon: Icons.home, color: Colors.teal),
  AacItem.word('hospital', icon: Icons.local_hospital, color: Colors.red),
  AacItem.word('room', icon: Icons.meeting_room, color: Colors.teal),
  AacItem.word('kitchen', icon: Icons.kitchen, color: Colors.orange),
  AacItem.word('bathroom', icon: Icons.wc, color: Colors.indigo),
  AacItem.word('school', icon: Icons.school, color: Colors.blue),
  AacItem.word('store', icon: Icons.store, color: Colors.green),
  AacItem.word('park', icon: Icons.park, color: Colors.green),
  AacItem.word('church', icon: Icons.church, color: Colors.purple),
  AacItem.word('outside', icon: Icons.wb_sunny, color: Colors.orange),
  AacItem.word('car', icon: Icons.directions_car, color: Colors.blueGrey),
  AacItem.word('work', icon: Icons.work, color: Colors.brown),
  AacItem.word('pharmacy', icon: Icons.local_pharmacy, color: Colors.red),
  AacItem.word('library', icon: Icons.local_library, color: Colors.brown),
  AacItem.word('cafeteria', icon: Icons.restaurant, color: Colors.orange),
  AacItem.word('beach', icon: Icons.beach_access, color: Colors.lightBlue),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeThings = <AacItem>[
  AacItem.word('phone', icon: Icons.smartphone, color: Colors.blue),
  AacItem.word('book', icon: Icons.menu_book, color: Colors.brown),
  AacItem.word('TV', icon: Icons.tv, color: Colors.blueGrey),
  AacItem.word('chair', icon: Icons.chair, color: Colors.brown),
  AacItem.word('cup', icon: Icons.local_cafe, color: Colors.orange),
  AacItem.word('plate', icon: Icons.dinner_dining, color: Colors.blueGrey),
  AacItem.word('remote', icon: Icons.settings_remote, color: Colors.grey),
  AacItem.word('clothes', icon: Icons.checkroom, color: Colors.indigo),
  AacItem.word('bag', icon: Icons.shopping_bag, color: Colors.brown),
  AacItem.word('keys', icon: Icons.key, color: Colors.amber),
  AacItem.word('computer', icon: Icons.computer, color: Colors.blue),
  AacItem.word('light', icon: Icons.lightbulb, color: Colors.amber),
  AacItem.word('window', icon: Icons.window, color: Colors.lightBlue),
  AacItem.word('door', icon: Icons.door_front_door, color: Colors.brown),
  AacItem.word('pillow', icon: Icons.bedroom_child, color: Colors.indigo),
  AacItem.word('blanket', icon: Icons.bedroom_parent, color: Colors.lightBlue),
  AacItem.word('paper', icon: Icons.description, color: Colors.blueGrey),
  AacItem.word('pen', icon: Icons.edit, color: Colors.blue),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringePeople = <AacItem>[
  AacItem.word('mom', icon: Icons.woman, color: Colors.pink),
  AacItem.word('dad', icon: Icons.man, color: Colors.blue),
  AacItem.word('sister', icon: Icons.girl, color: Colors.pink),
  AacItem.word('brother', icon: Icons.boy, color: Colors.blue),
  AacItem.word('friend', icon: Icons.people, color: Colors.teal),
  AacItem.word('baby', icon: Icons.child_care, color: Colors.orange),
  AacItem.word('teacher', icon: Icons.school, color: Colors.indigo),
  AacItem.word('nurse', icon: Icons.local_hospital, color: Colors.red),
  AacItem.word('doctor', icon: Icons.medical_services, color: Colors.blue),
  AacItem.word('family', icon: Icons.family_restroom, color: Colors.pink),
  AacItem.word('staff', icon: Icons.badge, color: Colors.blueGrey),
  AacItem.word('neighbor', icon: Icons.holiday_village, color: Colors.green),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeTime = <AacItem>[
  AacItem.word('morning', icon: Icons.wb_twilight, color: Colors.orange),
  AacItem.word('afternoon', icon: Icons.wb_sunny, color: Colors.amber),
  AacItem.word('night', icon: Icons.nightlight, color: Colors.indigo),
  AacItem.word('yesterday', icon: Icons.history, color: Colors.purple),
  AacItem.word('weekend', icon: Icons.weekend, color: Colors.teal),
  AacItem.word('week', icon: Icons.date_range, color: Colors.purple),
  AacItem.word('month', icon: Icons.calendar_month, color: Colors.purple),
  AacItem.word('year', icon: Icons.calendar_today, color: Colors.purple),
  AacItem.word('minute', icon: Icons.timer, color: Colors.blueGrey),
  AacItem.word('hour', icon: Icons.hourglass_bottom, color: Colors.blueGrey),
  AacItem.word('schedule', icon: Icons.event_note, color: Colors.indigo),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeLeisure = <AacItem>[
  AacItem.word('music', icon: Icons.music_note, color: Colors.deepPurple),
  AacItem.word('movie', icon: Icons.movie, color: Colors.indigo),
  AacItem.word('TV', icon: Icons.tv, color: Colors.blueGrey),
  AacItem.word('game', icon: Icons.sports_esports, color: Colors.green),
  AacItem.word('walk', icon: Icons.directions_walk, color: Colors.teal),
  AacItem.word('visit', icon: Icons.diversity_3, color: Colors.pink),
  AacItem.word('party', icon: Icons.celebration, color: Colors.orange),
  AacItem.word('hobby', icon: Icons.interests, color: Colors.purple),
  AacItem.word('puzzle', icon: Icons.extension, color: Colors.amber),
  AacItem.word('rest', icon: Icons.hotel, color: Colors.blueGrey),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringePhrases = <AacItem>[
  AacItem(
    label: 'I want that',
    speak: 'I want that',
    icon: Icons.touch_app,
    color: Colors.indigo,
  ),
  AacItem(
    label: "Let's go",
    speak: "Let's go",
    icon: Icons.directions,
    color: Colors.green,
  ),
  AacItem(
    label: "I don't know",
    speak: "I don't know",
    icon: Icons.help_outline,
    color: Colors.blueGrey,
  ),
  AacItem.word('maybe', icon: Icons.thumbs_up_down, color: Colors.orange),
  AacItem(
    label: 'Not now',
    speak: 'Not now',
    icon: Icons.event_busy,
    color: Colors.red,
  ),
  AacItem(
    label: "That's mine",
    speak: "That's mine",
    icon: Icons.back_hand,
    color: Colors.deepOrange,
  ),
  AacItem(
    label: 'Tell me more',
    speak: 'Tell me more',
    icon: Icons.forum,
    color: Colors.indigo,
  ),
  AacItem(
    label: 'I changed my mind',
    speak: 'I changed my mind',
    icon: Icons.sync,
    color: Colors.purple,
  ),
  AacItem(
    label: "I don't like it",
    speak: "I don't like it",
    icon: Icons.thumb_down,
    color: Colors.red,
  ),
  AacItem(
    label: 'I like it',
    speak: 'I like it',
    icon: Icons.thumb_up,
    color: Colors.green,
  ),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeReligion = <AacItem>[
  AacItem.word('pray', icon: Icons.volunteer_activism, color: Colors.purple),
  AacItem.word('God', icon: Icons.wb_sunny, color: Colors.amber),
  AacItem.word('church', icon: Icons.church, color: Colors.purple),
  AacItem.word('chaplain', icon: Icons.person, color: Colors.indigo),
  AacItem.word('blessing', icon: Icons.spa, color: Colors.teal),
  AacItem.word('faith', icon: Icons.favorite, color: Colors.red),
  AacItem.word('peace', icon: Icons.spa, color: Colors.green),
  AacItem.word('bible', icon: Icons.menu_book, color: Colors.brown),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeSchool = <AacItem>[
  AacItem.word('class', icon: Icons.class_, color: Colors.blue),
  AacItem.word('teacher', icon: Icons.school, color: Colors.indigo),
  AacItem.word('homework', icon: Icons.assignment, color: Colors.orange),
  AacItem.word('book', icon: Icons.menu_book, color: Colors.brown),
  AacItem.word('desk', icon: Icons.desk, color: Colors.blueGrey),
  AacItem.word('recess', icon: Icons.park, color: Colors.green),
  AacItem.word('bus', icon: Icons.directions_bus, color: Colors.amber),
  AacItem.word('test', icon: Icons.quiz, color: Colors.red),
  AacItem.word('learn', icon: Icons.lightbulb, color: Colors.orange),
  AacItem.word('friend', icon: Icons.people, color: Colors.teal),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeSport = <AacItem>[
  AacItem.word('ball', icon: Icons.sports_baseball, color: Colors.orange),
  AacItem.word('play', icon: Icons.sports, color: Colors.green),
  AacItem.word('team', icon: Icons.groups, color: Colors.blue),
  AacItem.word('win', icon: Icons.emoji_events, color: Colors.amber),
  AacItem.word('lose', icon: Icons.trending_down, color: Colors.blueGrey),
  AacItem.word('run', icon: Icons.directions_run, color: Colors.green),
  AacItem.word('swim', icon: Icons.pool, color: Colors.lightBlue),
  AacItem.word('walk', icon: Icons.directions_walk, color: Colors.teal),
  AacItem.word('exercise', icon: Icons.fitness_center, color: Colors.red),
  AacItem.word('game', icon: Icons.sports_score, color: Colors.indigo),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeAdjectives = <AacItem>[
  AacItem.word('clean', icon: Icons.soap, color: Colors.lightBlue),
  AacItem.word('dirty', icon: Icons.recycling, color: Colors.brown),
  AacItem.word('fast', icon: Icons.speed, color: Colors.red),
  AacItem.word('slow', icon: Icons.slow_motion_video, color: Colors.blueGrey),
  AacItem.word('new', icon: Icons.fiber_new, color: Colors.green),
  AacItem.word('old', icon: Icons.hourglass_empty, color: Colors.brown),
  AacItem.word('loud', icon: Icons.volume_up, color: Colors.deepOrange),
  AacItem.word('quiet', icon: Icons.volume_off, color: Colors.indigo),
  AacItem.word('pretty', icon: Icons.auto_awesome, color: Colors.pink),
  AacItem.word('funny', icon: Icons.mood, color: Colors.amber),
  AacItem.word('hard', icon: Icons.fitness_center, color: Colors.blueGrey),
  AacItem.word('easy', icon: Icons.sentiment_satisfied, color: Colors.green),
  AacItem.word('full', icon: Icons.battery_full, color: Colors.green),
  AacItem.word('empty', icon: Icons.battery_0_bar, color: Colors.orange),
  AacItem.word('wet', icon: Icons.water_drop, color: Colors.blue),
  AacItem.word('dry', icon: Icons.wb_sunny, color: Colors.amber),
  AacItem.word('open', icon: Icons.door_front_door, color: Colors.teal),
  AacItem.word('closed', icon: Icons.door_back_door, color: Colors.blueGrey),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeVerbs = <AacItem>[
  AacItem.word('eat', icon: Icons.restaurant, color: Colors.orange),
  AacItem.word('drink', icon: Icons.local_drink, color: Colors.blue),
  AacItem.word('sleep', icon: Icons.bedtime, color: Colors.indigo),
  AacItem.word('walk', icon: Icons.directions_walk, color: Colors.teal),
  AacItem.word('sit', icon: Icons.chair, color: Colors.brown),
  AacItem.word('stand', icon: Icons.accessibility_new, color: Colors.green),
  AacItem.word('open', icon: Icons.lock_open, color: Colors.teal),
  AacItem.word('close', icon: Icons.lock, color: Colors.blueGrey),
  AacItem.word('play', icon: Icons.sports_esports, color: Colors.green),
  AacItem.word('watch', icon: Icons.visibility, color: Colors.indigo),
  AacItem.word('listen', icon: Icons.hearing, color: Colors.purple),
  AacItem.word('come', icon: Icons.login, color: Colors.green),
  AacItem.word('leave', icon: Icons.logout, color: Colors.red),
  AacItem.word('start', icon: Icons.play_arrow, color: Colors.green),
  AacItem.word('finish', icon: Icons.check, color: Colors.blue),
  AacItem.word('try', icon: Icons.replay, color: Colors.orange),
  AacItem.word('call', icon: Icons.call, color: Colors.green),
  AacItem.word('read', icon: Icons.menu_book, color: Colors.brown),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeCreate = <AacItem>[
  AacItem.word('draw', icon: Icons.draw, color: Colors.pink),
  AacItem.word('paint', icon: Icons.brush, color: Colors.purple),
  AacItem.word('write', icon: Icons.edit, color: Colors.indigo),
  AacItem.word('build', icon: Icons.handyman, color: Colors.orange),
  AacItem.word('color', icon: Icons.palette, color: Colors.red),
  AacItem.word('cut', icon: Icons.content_cut, color: Colors.blueGrey),
  AacItem.word('glue', icon: Icons.attachment, color: Colors.amber),
  AacItem.word('photo', icon: Icons.photo_camera, color: Colors.blue),
  AacItem.word('sing', icon: Icons.mic, color: Colors.deepPurple),
  AacItem.word('dance', icon: Icons.nightlife, color: Colors.pink),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeDailyLife = <AacItem>[
  AacItem.word('wake up', icon: Icons.alarm, color: Colors.orange),
  AacItem.word('eat', icon: Icons.restaurant, color: Colors.orange),
  AacItem.word('wash', icon: Icons.soap, color: Colors.lightBlue),
  AacItem.word('dress', icon: Icons.checkroom, color: Colors.indigo),
  AacItem.word('brush teeth', icon: Icons.cleaning_services, color: Colors.teal),
  AacItem.word('medicine', icon: Icons.medication, color: Colors.red),
  AacItem.word('rest', icon: Icons.hotel, color: Colors.blueGrey),
  AacItem.word('sleep', icon: Icons.bedtime, color: Colors.indigo),
  AacItem.word('cook', icon: Icons.soup_kitchen, color: Colors.deepOrange),
  AacItem.word('clean', icon: Icons.cleaning_services, color: Colors.green),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeLetsTalk = <AacItem>[
  AacItem.word('hello', icon: Icons.waving_hand, color: Colors.orange),
  AacItem.word('goodbye', icon: Icons.waving_hand, color: Colors.blueGrey),
  AacItem(
    label: 'How are you?',
    speak: 'How are you?',
    icon: Icons.chat,
    color: Colors.indigo,
  ),
  AacItem(
    label: "I'm fine",
    speak: "I'm fine",
    icon: Icons.sentiment_satisfied,
    color: Colors.green,
  ),
  AacItem.word('talk', icon: Icons.record_voice_over, color: Colors.indigo),
  AacItem.word('listen', icon: Icons.hearing, color: Colors.purple),
  AacItem(
    label: 'Tell me',
    speak: 'Tell me',
    icon: Icons.forum,
    color: Colors.teal,
  ),
  AacItem(
    label: 'I agree',
    speak: 'I agree',
    icon: Icons.thumb_up,
    color: Colors.green,
  ),
  AacItem(
    label: "I disagree",
    speak: 'I disagree',
    icon: Icons.thumb_down,
    color: Colors.red,
  ),
  AacItem(
    label: "What's new?",
    speak: "What's new?",
    icon: Icons.newspaper,
    color: Colors.blue,
  ),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeMotorPlay = <AacItem>[
  AacItem.word('catch', icon: Icons.sports_baseball, color: Colors.orange),
  AacItem.word('throw', icon: Icons.sports_handball, color: Colors.green),
  AacItem.word('jump', icon: Icons.sports_gymnastics, color: Colors.purple),
  AacItem.word('run', icon: Icons.directions_run, color: Colors.red),
  AacItem.word('dance', icon: Icons.nightlife, color: Colors.pink),
  AacItem.word('clap', icon: Icons.sign_language, color: Colors.amber),
  AacItem.word('kick', icon: Icons.sports_soccer, color: Colors.green),
  AacItem.word('push', icon: Icons.arrow_forward, color: Colors.blue),
  AacItem.word('pull', icon: Icons.arrow_back, color: Colors.indigo),
  AacItem.word('spin', icon: Icons.sync, color: Colors.teal),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeOutAbout = <AacItem>[
  AacItem(
    label: 'Go out',
    speak: 'I want to go out',
    icon: Icons.logout,
    color: Colors.green,
  ),
  AacItem.word('car', icon: Icons.directions_car, color: Colors.blueGrey),
  AacItem.word('walk', icon: Icons.directions_walk, color: Colors.teal),
  AacItem.word('store', icon: Icons.store, color: Colors.orange),
  AacItem.word('park', icon: Icons.park, color: Colors.green),
  AacItem.word('restaurant', icon: Icons.restaurant, color: Colors.deepOrange),
  AacItem.word('bus', icon: Icons.directions_bus, color: Colors.amber),
  AacItem.word('outside', icon: Icons.wb_sunny, color: Colors.orange),
  AacItem(
    label: 'Come back',
    speak: 'I want to come back',
    icon: Icons.home,
    color: Colors.indigo,
  ),
  AacItem.word('map', icon: Icons.map, color: Colors.teal),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeReading = <AacItem>[
  AacItem.word('book', icon: Icons.menu_book, color: Colors.brown),
  AacItem.word('story', icon: Icons.auto_stories, color: Colors.indigo),
  AacItem.word('page', icon: Icons.find_in_page, color: Colors.blueGrey),
  AacItem.word('read', icon: Icons.menu_book, color: Colors.teal),
  AacItem.word('look', icon: Icons.visibility, color: Colors.blue),
  AacItem.word('picture', icon: Icons.image, color: Colors.purple),
  AacItem.word('word', icon: Icons.text_fields, color: Colors.indigo),
  AacItem.word('letter', icon: Icons.abc, color: Colors.orange),
  AacItem.word('quiet', icon: Icons.volume_off, color: Colors.blueGrey),
  AacItem.word('library', icon: Icons.local_library, color: Colors.brown),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const fringeToys = <AacItem>[
  AacItem.word('toy', icon: Icons.toys, color: Colors.amber),
  AacItem.word('ball', icon: Icons.sports_baseball, color: Colors.orange),
  AacItem.word('doll', icon: Icons.child_care, color: Colors.pink),
  AacItem.word('blocks', icon: Icons.view_module, color: Colors.red),
  AacItem.word('game', icon: Icons.sports_esports, color: Colors.green),
  AacItem.word('puzzle', icon: Icons.extension, color: Colors.purple),
  AacItem.word('cards', icon: Icons.style, color: Colors.indigo),
  AacItem.word('play', icon: Icons.play_arrow, color: Colors.green),
  AacItem.word('share', icon: Icons.share, color: Colors.teal),
  AacItem.word('turn', icon: Icons.rotate_right, color: Colors.blue),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const basicRequests = <AacItem>[
  AacItem.word('want', icon: Icons.favorite, color: Colors.amber),
  AacItem.word('more', icon: Icons.add, color: Colors.amber),
  AacItem.word('different', icon: Icons.shuffle, color: Colors.amber),
  AacItem.word('again', icon: Icons.replay, color: Colors.amber),
  AacItem.word('help', icon: Icons.help, color: Colors.amber),
  AacItem.word('stop', icon: Icons.stop_circle, color: Colors.red),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const basicChoices = <AacItem>[
  AacItem.word('yes', icon: Icons.check_circle, color: Colors.green),
  AacItem.word('no', icon: Icons.cancel, color: Colors.blueGrey),
  AacItem.word('good', icon: Icons.thumb_up, color: Colors.green),
  AacItem.word('bad', icon: Icons.thumb_down, color: Colors.blueGrey),
  AacItem.word('like', icon: Icons.favorite, color: Colors.pink),
  AacItem.word("don't like", icon: Icons.heart_broken, color: Colors.blueGrey),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const basicActions = <AacItem>[
  AacItem.word('go', icon: Icons.directions_walk, color: Colors.green),
  AacItem.word('get', icon: Icons.back_hand, color: Colors.green),
  AacItem.word('eat', icon: Icons.restaurant, color: Colors.orange),
  AacItem.word('drink', icon: Icons.local_drink, color: Colors.blue),
  AacItem.word('play', icon: Icons.sports_esports, color: Colors.green),
  AacItem.word('look', icon: Icons.visibility, color: Colors.teal),
  AacItem.word('do', icon: Icons.handyman, color: Colors.green),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const basicPeopleSocial = <AacItem>[
  AacItem.word('I', icon: Icons.person, color: Colors.blue),
  AacItem.word('you', icon: Icons.person_outline, color: Colors.blue),
  AacItem.word('my', icon: Icons.badge, color: Colors.blue),
  AacItem.word('hello', icon: Icons.waving_hand, color: Colors.pink),
  AacItem.word('goodbye', icon: Icons.exit_to_app, color: Colors.pink),
  AacItem.word('please', icon: Icons.favorite, color: Colors.pink),
  AacItem.word('thank you', icon: Icons.volunteer_activism, color: Colors.red),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const basicNeedsFeelings = <AacItem>[
  AacItem.word('hurt', icon: Icons.healing, color: Colors.deepOrange),
  AacItem.word('tired', icon: Icons.hotel, color: Colors.blueGrey),
  AacItem.word('thirsty', icon: Icons.water_drop, color: Colors.blue),
  AacItem.word('hungry', icon: Icons.restaurant, color: Colors.orange),
  AacItem.word('hot', icon: Icons.whatshot, color: Colors.red),
  AacItem.word('cold', icon: Icons.ac_unit, color: Colors.lightBlue),
  AacItem.word('happy', icon: Icons.sentiment_satisfied, color: Colors.amber),
  AacItem.word('sad', icon: Icons.sentiment_dissatisfied, color: Colors.indigo),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const basicStarters = <AacItem>[
  AacItem(
    label: 'I want…',
    icon: Icons.format_quote,
    color: Colors.indigo,
  ),
  AacItem(
    label: 'I need…',
    icon: Icons.format_quote,
    color: Colors.indigo,
  ),
  AacItem(
    label: 'I like…',
    icon: Icons.format_quote,
    color: Colors.indigo,
  ),
  AacItem(
    label: "I don't like…",
    icon: Icons.format_quote,
    color: Colors.indigo,
  ),
  AacItem(
    label: 'I feel…',
    icon: Icons.format_quote,
    color: Colors.indigo,
  ),
  AacVocabulary.yes,
  AacVocabulary.no,
];

const basicTopicWords = <AacItem>[
  AacItem.word('food', icon: Icons.restaurant, color: Colors.orange),
  AacItem.word('drinks', icon: Icons.local_drink, color: Colors.blue),
  AacItem.word('people', icon: Icons.groups, color: Colors.pink),
  AacItem.word('places', icon: Icons.place, color: Colors.teal),
  AacItem.word('activities', icon: Icons.sports_soccer, color: Colors.green),
  AacItem.word('toys', icon: Icons.toys, color: Colors.amber),
  AacItem.word('body', icon: Icons.accessibility_new, color: Colors.deepOrange),
  AacItem.word('clothing', icon: Icons.checkroom, color: Colors.indigo),
  AacItem.word('school', icon: Icons.school, color: Colors.blue),
  AacItem.word('animals', icon: Icons.pets, color: Colors.brown),
  AacVocabulary.yes,
  AacVocabulary.no,
];
