// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc1bZCh2AXuEiXKAUUDcpzzh-NwwjteA0',
    appId: '1:125703491571:web:c4f1f02747faee6ab18c86',
    messagingSenderId: '125703491571',
    projectId: 'humaniq-953d7',
    authDomain: 'humaniq-953d7.firebaseapp.com',
    storageBucket: 'humaniq-953d7.firebasestorage.app',
    measurementId: 'G-4KZEQ27QZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSr3KPlFydR1iLCpmXMiq1IesSe2dKA-Y',
    appId: '1:125703491571:android:6251bc57b5af6dbdb18c86',
    messagingSenderId: '125703491571',
    projectId: 'humaniq-953d7',
    storageBucket: 'humaniq-953d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDOrcLJ9D7Q962-COcZUAeNwkM09R-JXs',
    appId: '1:125703491571:ios:f884b0eca11675a8b18c86',
    messagingSenderId: '125703491571',
    projectId: 'humaniq-953d7',
    storageBucket: 'humaniq-953d7.firebasestorage.app',
    iosBundleId: 'com.jenayteris.swiftspeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDOrcLJ9D7Q962-COcZUAeNwkM09R-JXs',
    appId: '1:125703491571:ios:f884b0eca11675a8b18c86',
    messagingSenderId: '125703491571',
    projectId: 'humaniq-953d7',
    storageBucket: 'humaniq-953d7.firebasestorage.app',
    iosBundleId: 'com.jenayteris.swiftspeak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc1bZCh2AXuEiXKAUUDcpzzh-NwwjteA0',
    appId: '1:125703491571:web:60ab02fe438cb473b18c86',
    messagingSenderId: '125703491571',
    projectId: 'humaniq-953d7',
    authDomain: 'humaniq-953d7.firebaseapp.com',
    storageBucket: 'humaniq-953d7.firebasestorage.app',
    measurementId: 'G-2CJ42H3WYF',
  );
}
